import { type Task } from "@/types/task";

export const exampleTasks: Task[] = [
  {
    id: "1",
    name: "Eatchanged",
    category: "daily",
    dailyCountTotal: 2,
    dailyCountFinished: 0,
    currentStreak: 0,
    highestStreak: 0,
  },
  {
    id: "2",
    name: "Play new",
    category: "weekly",
    repeatFrequency: 3,
    repeatDays: ["Monday", "Thursday", "Wednesday"],
    currentStreak: 3,
    highestStreak: 20,
  },
  {
    id: "3",
    name: "Eat again",
    category: "daily",
    dailyCountTotal: 1,
    dailyCountFinished: 0,
    currentStreak: 15,
    highestStreak: 15,
  },
  {
    id: "4",
    name: "Eat once morerr",
    category: "daily",
    dailyCountTotal: 5,
    dailyCountFinished: 2,
    currentStreak: 300,
    highestStreak: 1000,
  },
  {
    id: "5",
    name: "Eat - yeah",
    category: "daily",
    dailyCountTotal: 3,
    dailyCountFinished: 1,
    currentStreak: 0,
    highestStreak: 0,
  },
  {
    id: "6",
    name: "Sleep",
    category: "xdays",
    xValue: 3,
    startDate: new Date(),
    currentStreak: 20,
    highestStreak: 60,
  },
  {
    id: "7",
    name: "Play",
    category: "weekly",
    repeatFrequency: 3,
    repeatDays: ["Monday", "Thursday", "Wednesday"],
    currentStreak: 0,
    highestStreak: 100,
  },
  {
    id: "8",
    name: "Repeat",
    category: "monthly",
    repeatFrequency: 2,
    repeatDays: ["1st", "last-date"],
    currentStreak: 7,
    highestStreak: 50,
  },
];
